### ISSUE TITLE
Validation failure

### ISSUE THREAD

**Issue by Kuoxsr** [ajacocks/autofs-aur#1]
This issue affects version 5.1.9 of autofs as of this morning (4:59AM US Central - 2024-08-14)

In the PKGBUILD file, the sha256sum listed for patch_order_5.1.9 is `d01c9e90ba750c1a5de71ffcac9a778810a335925a4d2579d3231414de4f43f1`

However, in reality ...
```bash
curl https://mirrors.edge.kernel.org/pub/linux/daemons/autofs/v5/patches-5.2.0/patch_order_5.1.9 | sha256sum
```

... the actual checksum is `ef6abcb1a164b5474c41e9d4de1cafcda769173e7f60d80ed90e75e4f3209f12`

The package fails to install due to "ERROR: One or more files did not pass the validity check!"

I assume they changed the file after this PKGBUILD was uploaded.

**Comment by ajacocks** [comment]
They added a ton more patches, which I have added to the AUR PKGBUILD. Thanks!

**Comment by Kuoxsr** [comment]
Unfortunately, I still cannot install autofs this morning (autofs-5.1.9-4).  I'm still getting a validation error:
![Screenshot_20240814_124928](https://github.com/user-attachments/assets/3b5da42a-8bed-4901-948a-6eceafa6bb45)

Looking at the PKGBUILD file, the checksum for patch_order_5.1.9 is still `d01c9e90ba750c1a5de71ffcac9a778810a335925a4d2579d3231414de4f43f1`, but when I do the following command, using the URL from the PKGBUILD:

```bash
curl https://mirrors.edge.kernel.org/pub/linux/daemons/autofs/v5/patches-5.2.0/patch_order_5.1.9 | sha256sum
```

... I get a checksum of `ef6abcb1a164b5474c41e9d4de1cafcda769173e7f60d80ed90e75e4f3209f12`

Is my assumption correct?  Is this the source of the validation error?
